#!/bin/sh
# with_output — write a result file to work/out/, register it via fd3,
# then succeed. The dispatcher will TOCTOU-collect the output and stage it.
set -e
mkdir -p "$LETTS_WORKDIR/out"
{
    echo "Generated by mission $LETTS_MISSION_ID"
    echo "Timestamp: $(date)"
    echo "Args: $*"
} > "$LETTS_WORKDIR/out/result"

printf '{"event":"output_file","key":"result"}\n' >&3
printf '{"event":"success","return":{"size":%d}}\n' "$(wc -c < "$LETTS_WORKDIR/out/result")" >&3
exit 0
